- hosts: localhost
  become: true
  tasks:
  - name: Update apt packages
    apt:
      update_cache: yes
  - name: Install pip
    apt:
      name: python-pip
      state: present
  # - name: Install virtualenv
  #   apt:
  #     name: python3-venv
  #     state: present
  - name: Import docker tasks
    include_tasks: docker.yml
  